services:
  - type: web
    name: digitalmart
    env: docker # <--- ဒီနေရာ ပြောင်းလိုက်တာပါ
    plan: free
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        sync: false
